### ISSUE TITLE
раздел коммьюнити/вопросы

### ISSUE THREAD

**Issue by releu** [gistflow/gistflow#10]
лайк твиттер, только подписка не на юзера а на тег

**Comment by releu** [comment]
я хочу чтобы был простой свободный раздел где любой зарегистрированный пользователь мог бы писать небольшие посты и вопросы.

пока можно сделать через STI в Posts и разделить сайт на вкладки Posts или Articles и Community, чтобы фильтровать результаты и показывать немного разные интерфейсы..

идеологически сайт разделяется на часть постов (серьезная интересная часть) и на неформальное общение, даже треп людей "в теме".

Но вот если предположить что у нас все таки будет большое количество пользователей, надо делать одно в постгресе, а комьюнити в носкуэле. там поиск нафиг не нужен..

**Comment by makaroni4** [comment]
Боюсь, что коммьюнити будут выглядеть вот так (я тут начал NoName подкаст слушать вместо музыки по утрам):

http://mi.rpod.ru/261445.html#c307661

**Comment by releu** [comment]
ужасно. у нас будет намного лучше
