### ISSUE TITLE
Bug: names from the @ prompt are always put to the bottom of the post

### ISSUE THREAD

**Issue by YakovL** [gistflow/gistflow#112]
How to reproduce:
1. create a reply anywhere (with at least 1 other participant)
2. write something (but don't send the reply)
3. put @ not to the end of the reply -- for instance, to the top of it
4. chose a name from the prompt

What is expected to happen:

the name should be added after the @.

What actually happens:

the name is put to the bottom of the reply (to the end, after all other text).

**Comment by releu** [comment]
fixed
