### ISSUE TITLE
Like/Unlike for posts and comments

### ISSUE THREAD

**Issue by makaroni4** [gistflow/gistflow#14]
I think it would be great to implement smth like in habrahabr.ru where you can like or unlike any post or comment.

**Comment by releu** [comment]
I like a Facebook like button, because it can only increments a counter of likes and posts with negative rating will never be.
Many trolls like to decrease posts rating if they can.

**Comment by makaroni4** [comment]
I like it, just positive rating and it is easy from the interface point of view - just one thumb-up button (ajax, user can't undo like)

**Comment by releu** [comment]
maybe its should be named awesome? The post has 37 awesomes =)

**Comment by makaroni4** [comment]
Or thumb-ups )
