### ISSUE TITLE
Unlike post

### ISSUE THREAD

**Issue by Fodoj** [gistflow/gistflow#154]
I liked my own post accidentally and now I can't unlike it.

**Comment by releu** [comment]
Hmm.. Ok. User should always have an undo button.

Thanks :)

**Comment by makaroni4** [comment]
Working on it, actually I have fixed this but stuck with capybara POST ajax requests – seems like it is always GET. I will fix that and make PR asap.

**Comment by releu** [comment]
Are you using `, js: true` ?

**Comment by makaroni4** [comment]
For sure :smile:

**Comment by makaroni4** [comment]
https://github.com/gistflow/gistflow/pull/199

**Comment by makaroni4** [comment]
Fixed
