### ISSUE TITLE
Email titles should be consistent

### ISSUE THREAD

**Issue by skammer** [gistflow/gistflow#182]
Now I get tons of email like "username commented on post X" and my email client is too stupid to group them together.

I suggest to title all comment notification emails as "New comment on post X" and stop this madness.

![derp](http://ragefaces.s3.amazonaws.com/5041e2b2ae7c704e2800000d/derp.png)

**Comment by releu** [comment]
+1. Thanks

**Comment by releu** [comment]
fixed
