### ISSUE TITLE
http://gistflow.com/auth/twitter does not work

### ISSUE THREAD

**Issue by killthekitten** [gistflow/gistflow#194]
When callback fires, all fails. By the way... where is `account/twitter_controller.rb` which is used by routes.rb?

**Comment by releu** [comment]
Twitter will be removed from gistflow. One day I done it, but somehow it reverts.. may be with bugs.

**Comment by killthekitten** [comment]
What was the reason to remove it?

**Comment by releu** [comment]
We wanna replace it with twitter share button. Thus all users are possible to share posts.

Two ways of sharing is a little complicated for users.

**Comment by releu** [comment]
removed
