### ISSUE TITLE
Introduce Gistflow on the Code Triage

### ISSUE THREAD

**Issue by killthekitten** [gistflow/gistflow#195]
I use http://www.codetriage.com/ almost for a month, and it is a cool place to find some contributors with a fresh mind for a project. We could introduce Gistflow there. How do you feel about it?

**Comment by makaroni4** [comment]
@killthekitten great idea!

I think that first we need to increase our test coverage and than introduce GF at Code Triage. We hope that we fix all issues before New Year so it seems like good start of the year – to present GF at Code Triage.
