### ISSUE TITLE
Weird issue with similar posts

### ISSUE THREAD

**Issue by killthekitten** [gistflow/gistflow#202]
http://gistflow.com/posts/586-debugging-sphinx-inside-a-rails-app

My post for some reason has two similar items (and each of them is linked with post itself).

**Comment by makaroni4** [comment]
@killthekitten we should add **uniq** to similar posts I think, let me do that

**Comment by killthekitten** [comment]
:+1:

**Comment by killthekitten** [comment]
Any changes?

**Comment by killthekitten** [comment]
Has it been deployed? Still got duplicates.

**Comment by releu** [comment]
Yep... Looks like joining tags creates doubles and distinct doesn't solve the problem.

**Comment by makaroni4** [comment]
Agree. I fixed issue with `except` method but this is another aspect. Let's write failing spec first.
