### ISSUE TITLE
Duplicates in notifications

### ISSUE THREAD

**Issue by makaroni4** [gistflow/gistflow#204]
![Screen Shot 2012-12-21 at 2 02 27 PM](https://f.cloud.github.com/assets/768070/26769/990416d6-4b55-11e2-83b3-0dd745d703a7.png)

**Comment by killthekitten** [comment]
Which of them has higher priority? I mean, we should introduce any :)

**Comment by releu** [comment]
I think mention is primary.

**Comment by makaroni4** [comment]
Fixed.
