### ISSUE TITLE
Codeclimate account

### ISSUE THREAD

**Issue by killthekitten** [gistflow/gistflow#211]
We're opensource. We're on github. We must use [codeclimate](http://codeclimate.com/). It's free and awesome :) Quickly, do it!

**Comment by releu** [comment]
Agree. At now this service is much better than 3 months ago.

**Comment by makaroni4** [comment]
Generating code quality metrics. Refresh at will.

Seems like codeclimate has an issue with fetching gistflow, I left feedback, lets wait a bit.

**Comment by makaroni4** [comment]
Added :)
