### ISSUE TITLE
Syntax highlight

### ISSUE THREAD

**Issue by vol4ok** [gistflow/gistflow#22]

**Comment by makaroni4** [comment]
``` ruby
puts "Lets use https://github.com/blog/881-linguist"
```

**Comment by makaroni4** [comment]
http://iamaust.in/posts/3
https://github.com/trevorturk/pygments

Search 'heroku' at
http://railscasts.com/episodes/272-markdown-with-redcarpet?view=comments

**Comment by makaroni4** [comment]
http://www.webdesignbooth.com/9-useful-javascript-syntax-highlighting-scripts/
