### ISSUE TITLE
User should be able to read all posts

### ISSUE THREAD

**Issue by makaroni4** [gistflow/gistflow#64]
I think the best solution to it - different walls.

One with all posts, one with post tagged with your tags and the one for posts by people user follows (in future).

**Comment by releu** [comment]
But I think it's not need. Why user want read all posts? Only interested.

**Comment by releu** [comment]
Only Google wants read all posts :)

**Comment by makaroni4** [comment]
FLOW | ALL

flow - Post.tagged_with my tags
all - All posts
