### ISSUE TITLE
Cool topics to write posts

### ISSUE THREAD

**Issue by makaroni4** [gistflow/gistflow#69]
1) DBAORS
2) Interview questions
3) Tests

**Comment by makaroni4** [comment]
4) Working examples (deployed to Heroku)

**Comment by makaroni4** [comment]
5) Gistflow implementation of different features like following, tagging and so on

**Comment by makaroni4** [comment]
6) #challenge tag with great programming tasks. Users submit the answers with gist or inline code.

**Comment by releu** [comment]
What'is not an issue. Moved to https://github.com/gistflow/gistflow/wiki/Cool-topics-to-write-posts
