### ISSUE TITLE
модель followers

### ISSUE THREAD

**Issue by releu** [gistflow/gistflow#7]
юзер в будующем сможет подписываться на теги. нужно собирать статистику по интеремующим его тегам (поста) для подсветки интеремных ему

**Comment by makaroni4** [comment]
Можно заюзать готовый gem: https://github.com/mbleigh/acts-as-taggable-on (последнее обновление недавно совсем) или этот https://github.com/jviney/acts_as_taggable_on_steroids(год назад)

**Comment by releu** [comment]
Помоему как с авторизацией. Проще сделать самим, чтобы можно было расширить на функциональность статистики.

но название taggings можно повзаимствовать :)

**Comment by makaroni4** [comment]
Я думаю, что разумно будет поизучать код подобных гемов и посмотреть, как они оптимизируют запросы и т.п.
