### ISSUE TITLE
Комментарии к постам

### ISSUE THREAD

**Issue by makaroni4** [gistflow/gistflow#9]
Реализовать комменты, без древовидной структуры, но чтобы в коммент можно было добавить имя пользователя. Плюс ко всему вопросительные коменты можно выделять серым.

**Comment by makaroni4** [comment]
Пользователь может упоминать других пользователей в комменте (@makaroni4). После отправки коммента мы парсим его и создаем нотификейшены (отдельная модель)

**Comment by releu** [comment]
Нужно в MentionsParser передать текст. Текст парсится на @makaroni4 и пр, валидируется на наличие пользователей с этими username-ами в возвращается массив юзернеймов, которые надо превратить в ссылки.
