### ISSUE TITLE
Cut text

### ISSUE THREAD

**Issue by agentcooper** [gistflow/gistflow#94]
Make some visual label to show if there is a cut in the post. Right now, in the flow view, you need to click 'show' button to see if there is a cut in it.

Example: `<cut text="More tips"></cut>` with default text `Read full`

**Comment by makaroni4** [comment]
Regexp for it:

``` regexp
<cut(\stext\s?=\s?'.+')?\s?>
```

**Comment by releu** [comment]
Nice!
